development:
  adapter: postgresql
  database: development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: craiglist_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: craiglist_production
  pool: 5
  timeout: 5000
  url: <%= ENV['DATABASE_URL']%>
  
